[build]
  command = "rm -rf node_modules && npm install --legacy-peer-deps --force && npm run buildProd"
  publish = "dist/browser"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps --force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200